version: "3.7"
services:
  db:
    image: postgres:13.2-alpine
    container_name: 'postgres-docker'
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-assessment:/var/lib/postgresql/data
      - ./sql/data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
  backend:
    container_name: 'spring-boot-docker'
    build: ./
    image: spring-docker-jar:latest
    entrypoint: [ "java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar" ]
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
volumes:
  db-assessment:
