spring:
  datasource:
    url: jdbc:postgresql://localhost:32770/assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true



