dbto:
  datasource: driverClassName:org.postgresql.Driver
spring:
  datasource:
    url: jdbc:postgresql://localhost:32770/assessment
    username: postgres
    password: postgres
    security:
      oauth2:
#security:
#  user:
#    name: user
#    password: 12345678


  #??GraphQL??
  graphql:
    graphiql:
      enabled: true



