spring:
  datasource:
    url: jdbc:postgresql://db:5432/assessment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  graphql:
    graphiql:
      enabled: true
    cors:
      allowed-origins: '*'


